// Generated by gencpp from file my_mpc/my_marker.msg
// DO NOT EDIT!


#ifndef MY_MPC_MESSAGE_MY_MARKER_H
#define MY_MPC_MESSAGE_MY_MARKER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_mpc
{
template <class ContainerAllocator>
struct my_marker_
{
  typedef my_marker_<ContainerAllocator> Type;

  my_marker_()
    : car_x(0.0)
    , car_y(0.0)
    , ref_x(0.0)
    , ref_y(0.0)  {
    }
  my_marker_(const ContainerAllocator& _alloc)
    : car_x(0.0)
    , car_y(0.0)
    , ref_x(0.0)
    , ref_y(0.0)  {
  (void)_alloc;
    }



   typedef float _car_x_type;
  _car_x_type car_x;

   typedef float _car_y_type;
  _car_y_type car_y;

   typedef float _ref_x_type;
  _ref_x_type ref_x;

   typedef float _ref_y_type;
  _ref_y_type ref_y;





  typedef boost::shared_ptr< ::my_mpc::my_marker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_mpc::my_marker_<ContainerAllocator> const> ConstPtr;

}; // struct my_marker_

typedef ::my_mpc::my_marker_<std::allocator<void> > my_marker;

typedef boost::shared_ptr< ::my_mpc::my_marker > my_markerPtr;
typedef boost::shared_ptr< ::my_mpc::my_marker const> my_markerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_mpc::my_marker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_mpc::my_marker_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_mpc::my_marker_<ContainerAllocator1> & lhs, const ::my_mpc::my_marker_<ContainerAllocator2> & rhs)
{
  return lhs.car_x == rhs.car_x &&
    lhs.car_y == rhs.car_y &&
    lhs.ref_x == rhs.ref_x &&
    lhs.ref_y == rhs.ref_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_mpc::my_marker_<ContainerAllocator1> & lhs, const ::my_mpc::my_marker_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_mpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_mpc::my_marker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_mpc::my_marker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_mpc::my_marker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_mpc::my_marker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_mpc::my_marker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_mpc::my_marker_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_mpc::my_marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7abacc1e7af4db2ca418ecfedd0f34c";
  }

  static const char* value(const ::my_mpc::my_marker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7abacc1e7af4db2ULL;
  static const uint64_t static_value2 = 0xca418ecfedd0f34cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_mpc::my_marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_mpc/my_marker";
  }

  static const char* value(const ::my_mpc::my_marker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_mpc::my_marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 car_x\n"
"float32 car_y\n"
"float32 ref_x\n"
"float32 ref_y\n"
;
  }

  static const char* value(const ::my_mpc::my_marker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_mpc::my_marker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.car_x);
      stream.next(m.car_y);
      stream.next(m.ref_x);
      stream.next(m.ref_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_marker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_mpc::my_marker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_mpc::my_marker_<ContainerAllocator>& v)
  {
    s << indent << "car_x: ";
    Printer<float>::stream(s, indent + "  ", v.car_x);
    s << indent << "car_y: ";
    Printer<float>::stream(s, indent + "  ", v.car_y);
    s << indent << "ref_x: ";
    Printer<float>::stream(s, indent + "  ", v.ref_x);
    s << indent << "ref_y: ";
    Printer<float>::stream(s, indent + "  ", v.ref_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MPC_MESSAGE_MY_MARKER_H
